bind 0.0.0.0
port 0
masterauth <password>
tls-port 6379
tls-cert-file /etc/redis/certs/redis.crt
tls-key-file /etc/redis/certs/redis.key
tls-ca-cert-file /etc/redis/certs/ca.crt
tls-cluster yes
tls-auth-clients yes
requirepass <password>
tls-protocols "TLSv1.2 TLSv1.3"
tls-replication yes
repl-diskless-load on-empty-db